# Generated by Django 5.1 on 2024-08-23 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='タイトル')),
                ('content', models.CharField(blank=True, max_length=500, verbose_name='本文')),
                ('diary_date', models.DateField(blank=True, verbose_name='日付')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='筆者')),
            ],
        ),
    ]
