# Generated by Django 5.1 on 2024-08-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diary',
            table='tbl_diaries',
        ),
    ]
