# Generated by Django 5.1 on 2024-08-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'このユーザー名は既に使用されています。'}, max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
